repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
#    - id: cmake-lint
  - repo: git://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    - id: clang-format
