# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '*'
    tags: '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    env:
      CC: gcc-9
      CXX: g++-9
      BOOST_ROOT: $BOOST_ROOT_1_72_0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir build
        cd build

    - name: Setup initial environment
      run:
        cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE/CMakeLists.txt
    
    - name: Get targets
      run:
        make help
