# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '*'
    tags: '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    env:
      CC: gcc-9
      CXX: g++-9
      python_ROOT: /opt/hostedtoolcache/Python/3.8.3/x64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Runs a set of commands using the runners shell
      - name: Create build directory
        run: |
          mkdir build
          cd build
          ls $python_ROOT/lib

      - name: Cache external dependencies
        id: cache-external-boost
        uses: actions/cache@v2
        with:
          path: External/Root
          key: ${{ runner.os }}-build-external-3

      - name: Setup initial environment
        run:
          cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE/CMakeLists.txt

      - name: Setup initial environment
        run:
          make ExternalDependencies

      - name: Setup final environment
        run:
          cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE/CMakeLists.txt
        if: always()

      - name: Build release targets
        run:
          make mdf_iter_wheel
        if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: mdf_iter
          path: $GITHUB_WORKSPACE/Python/Distribution_Iterator/dist/
        if: always()
